@startuml

left to right direction

actor "User" as usr
actor "Administrator" as admin

rectangle "To Koutouki tou Manousou" {
  usecase "Login" as UC1
  usecase "View Dashboard" as UC2
  usecase "Logout" as UC3
  usecase "Manage Users" as UC4
}

usr -- UC1
usr -- UC2
usr -- UC3
admin -up- UC4

@enduml
