@startuml

left to right direction

actor "User" as usr
actor "Helpdesk" as hlpdsk
actor "Registered User" as r_usr
usr <|-- r_usr

rectangle "To Koutouki tou Manousou" {
  usecase "Login" as UC1
  usecase "Logout" as UC2
  usecase "Manage Users" as UC3
  usecase "Inform Message" as UC4
  usecase "Failure Message" as UC5





   usecase "Create" as UC13
   usecase "Recovery" as UC14











}

usr -- UC1
usr -- UC2
admin -up- UC3




r_usr -- UC13

















UC1 .> UC4 : include
UC2 .> UC4 : include
UC5 .> UC1 : extends





















@enduml
