@startuml

left to right direction

actor "User" as usr
actor "Silver User" as s_usr
actor "Administrator" as admin

rectangle "To Koutouki tou Manousou" {
  usecase "Login" as UC1
  usecase "Logout" as UC2
  usecase "Manage Users" as UC3
  usecase "Inform Message" as UC4
  usecase "Failure Message" as UC5
}

usr -- UC1
usr -- UC2
admin -up- UC3

UC1 .> UC4 : include
UC2 .> UC4 : include
UC5 .> UC1 : extends

usr <|-- s_usr



















@enduml
